# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Coding\first_order\first_order_gui_demo\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 591)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.source_image_label = QtWidgets.QLabel(self.groupBox_2)
        self.source_image_label.setText("")
        self.source_image_label.setObjectName("source_image_label")
        self.verticalLayout_2.addWidget(self.source_image_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.image_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.image_lineEdit.setObjectName("image_lineEdit")
        self.horizontalLayout_2.addWidget(self.image_lineEdit)
        self.image_open_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.image_open_pushButton.setObjectName("image_open_pushButton")
        self.horizontalLayout_2.addWidget(self.image_open_pushButton)
        self.horizontalLayout_2.setStretch(0, 4)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dv_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.dv_lineEdit.setObjectName("dv_lineEdit")
        self.horizontalLayout_3.addWidget(self.dv_lineEdit)
        self.gv_open_pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.gv_open_pushButton.setObjectName("gv_open_pushButton")
        self.horizontalLayout_3.addWidget(self.gv_open_pushButton)
        self.horizontalLayout_3.setStretch(0, 4)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.generate_pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.generate_pushButton.setObjectName("generate_pushButton")
        self.verticalLayout.addWidget(self.generate_pushButton)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addWidget(self.groupBox)
        self.fps_label = QtWidgets.QLabel(self.centralWidget)
        self.fps_label.setObjectName("fps_label")
        self.verticalLayout.addWidget(self.fps_label)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(2, 2)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Artificial Face Generation Model Demo"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Source Image"))
        self.image_open_pushButton.setText(_translate("MainWindow", "Open"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Driving Video"))
        self.gv_open_pushButton.setText(_translate("MainWindow", "Open"))
        self.generate_pushButton.setText(_translate("MainWindow", "Generate"))
        self.groupBox.setTitle(_translate("MainWindow", "Generated Video"))
        self.fps_label.setText(_translate("MainWindow", "Idle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
